### ISSUE TITLE
Example using authentication?

### ISSUE THREAD

**Issue by maxbates** [firebase/firebase-chrome-extension#1]
I've had trouble discerning whether it is possible to login a user using firebase simple login, and write to their firebase specifically (e.g. persisting credentials in localStorage). 

If it is, could someone tie that into the example here?

**Comment by adriaanlabusc** [comment]
I believe I'm trying to do what this issue refers to but using the new Firebase 3.0. Sign in is working on a hosted webpage using AuthUI and the google provider; I then get a token using  `user.getToken().then(function(accessToken) {...}))` which I store in local storage as you suggest.

The token is now accessible within the extension (content script on a different page, unknown url) and I tried using it to authenticate in a few ways `fireBaseApp.auth(token)` or `fireBaseApp.auth().signInWithCredential(token)` among other things. I get the error `This domain is not authorized for OAuth operations for your Firebase project`, but there is no domain since I'm in the extension, this is the same error I got when I tried to use AuthUI from within the extension.

Is something like this supposed to work, and if not, how can I authenticate from within a chrome extension?
